### ISSUE TITLE
"domain_dic" file missing

### ISSUE THREAD

**Issue by Ziki521** [MDhewei/protiler#2]
Failed to run the pipeline. It seems that there is a "domain_dic" file missing in the "StaticFiles" directory?

**Comment by Ziki521** [comment]
In "fielpath.py":
#domain_dic_file = os.path.join(RequiredFilePath, 'domain_dic')

**Comment by MDhewei** [comment]
Do you use pip install? If you install directly you need install lfs to
download those dict files.  I suggest you install the newest version
through pip, there should be no problem.

Best,
Wei
